server:
  port: 8003

mybatis:
  type-aliases-package: com.lishuai.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-locations: classpath:mybatis/mybatis-config.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db03?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

#Eureka 配置
eureka:
  client:
    service-url: #服务注册
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #要注册到的地址
  instance:
    instance-id: springcloud-provider-dept-8003 #修改默认描述信息
    prefer-ip-address: true


# info配置
info:
  # 项目的名称
  app.name: LiShuai.SpringCloud03
  # 公司的名称
  company.name: Tinker_Li